repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name:  "external-dns"
    chart: "bitnami/external-dns"
    namespace: "external-dns"
    version: {{ .Values | getOrNil "external_dns.version" | default "4.5.5" }}
    installed: {{ .Values | getOrNil "external_dns.installed" | default false }}
    labels:
      tier: external-dns
    values:
      - values.yaml.gotmpl
